### ISSUE TITLE
Program to open the file

### ISSUE THREAD

**Issue by SableyeFan** [auriorx/ptcgo-auto-redeemer-simple#1]
What file do I need to open to get to the redeemer and what program is needed to do it?

**Comment by auriorx** [comment]
The files in the GitHub repository are the source. You don't need that to run the application, it's just to show people nothing fishy is going on. 

You should see a "releases" tab while looking at the repository. That .zip file should contain a .exe file you can run.

~Auriorx

**Comment by SableyeFan** [comment]
Thank you

**Comment by SableyeFan** [comment]
What is the exit keybind to shut down the program and the windowed option doesn't work, but full screen does.
