### ISSUE TITLE
disable program and program misaligned

### ISSUE THREAD

**Issue by SableyeFan** [auriorx/ptcgo-auto-redeemer-simple#2]
whats the key command to disable the program and the alignment of the script is off
i could try to use full screen mode but then i cant reach the program

**Comment by auriorx** [comment]
Unfortunately, there's a technical reason why I cannot implement a disable function. I haven't figured out a to have the application execute keyboard commands and listen to a disable command as well. 

So I would suggest not spamming the application with 1000 codes, but start with 10 at a time just in case.

As for the windowed mode, try to make sure that your windowed instance is as close to full screen as possible. That's the way to make the code insertion work.

~Auriorx
